- egg_dropping_puzzle(DP).cpp
egg dropping puzzle using dynamic programming
> egg_dropping_puzzle(DP).cpp

- BinarySearch.java
> Binary Search

- README.md
- flask desktop app/app.py
- flask desktop app/templates/boot.html
- flask desktop app/templates/index.html
i have updated readme.md and uploaded simple desktop app using webgui and flask back end
> updated readme and added flask webgui desktop app

- MergeSortArray.js
- README.md
- Recursion.cpp
I hope this contribution can help someone."Update README.md file and Adding new solution"
> Update README.md file and Adding new programs

- Library_Management_System.c
Here, I've made a library management system in C language
> Added a library Management System

- gen_table.py
Made the code more **understandable** and **good-looking**. Also, **added name** for this file.
> Multiplication Table Generator

- Binary sorting in java
Hope you will merge this it will give help to open source repositories and me as well thanku
> Create Binary sorting in java

- README.md
- Tower of Hanoi
Tower of Hanoi solved using recursion
> Tower of hanoi (c++)

- Bubble_Sort.cpp
- Selection_Sort.cpp
Created Selection sort and Bubble sort algorithms using C++
> Create Selection Sort and Bubble Sort programs in C++

- README.md
Added my name in the README file
> Add name in README

- clock_thread.c
Implementation of a clock in C using multithreading.
> Added multithreading program in C clock_thread.c

- 3 Palindrome.py
- README.md
added one new program to get three palindrome if there in a single string and edited the readme
> Check The Changes

- python fibonacci series recursion
Do add this file to your repository if you find it useful.
> created a Python program to display the Fibonacci sequence

- Credit_card_validator.java
- README.md
> Added Credit Card Validator

- Grafo.java
- README.md
- Vertice.java
Java files inserted for Graphs and Vertices used in Dijkstra's algorithm
> Add Graph and Vertex for Dijkstra Algorithm

- README.md
- age scanner using java
i added few steps and also contributed by writing my name
> adding info how to contribute in steps

- Fibonacci(DP).cpp
Dynamic programming approach for finding nth term of fibonacci
where n is less than 1001
> Added fibonacci term calculator using DP

- fibonacci_upto_n_terms.cpp
Hi, 
I'm Shaik Fharook and a small contribution from my side. I've added Fibonacci series up to n terms in C++ language. Please find it.
> Added fibonacci series upto 'n' terms in cpp language

- ArrayManupulation.java
- README.md
> ArrayManupulation.java

- Binary to Decimal.c
Program for converting a Binary number into Decimal number using C language
> Binary to Decimal.c

- Math.java
- README.md
Added a basic java program to demonstrate arithmetic calculations.
> Added simple java program

- patternprogram.py
Output-
* 
* * 
* * * 
* * * * 
* * * * *
> Pattern Program in Python

- datacleaning2
This reports the column index and the number of unique values for each column, followed by the percentage of unique values out of all rows in the dataset.
> datacleaning2

- Selection sort
Hacktoberfest2020
Algorithm to implement selection sort on the array
> SelectionSort

- FizzBuzz.py
Created the FizzBuzz program in Python
> Create FizzBuzz program in Python

- open_addressing.cpp
> Hashing Concept

- Generating Password and OTP in Java
Many a time we forget our passwords and we opt for Forget password option and within no time we get a new password at our registered email-ID or phone no. to login our account. And every time we get a different password.
Sometimes we access our bank accounts while shopping from an online store or many more ways, in order to verify our transition from the bank account, they send us OTP(One Time Password) on our registered phone no. or our email-ID, within no time.
The following code explains how to generate such Passwords and OTP within no time and what code we can use if in case we need to do so.
> Generating Password and OTP in Java

- BinarySearch.java
- Trie_insert_search.cpp
just added the Trie data structure in c++ with insert and search operations.
> Added trie data structure in c++

- binarytree.c
added comments to describe the functions more clearly
> update binarytree.c 

- c codes/FIBONACC.C
- c codes/HCF2.C
- c codes/LCM2.C
Adding C codes for:
1. LCM
2. HCF
3. FIBONACCI SERIES
> Added basic C codes

- python codes/wordcount.py
the script displays the frequency of words in a text file.
> Added wordcount.py

- others/TempTables.sql
understanding temp tables in database
> TempTables

- interpolation_search.cpp
> interpolation search

- python-sorting-algorithms/heap-sort.py
> add heap sort with python

- python codes/Even_or_Odd.py
> Added Even_or_Odd.py

- c codes/calculatorusingswitch.c
created a simple calculator in c.
> calculatorusingswitch.c

- Object Oriented Programming/Bank_system_using_OOPS.cpp
- Object Oriented Programming/ContainershipOOPS.cpp
- Object Oriented Programming/EducationSystemOOPS.cpp
- Object Oriented Programming/bookshop_OOPS.cpp
- README.md
Hi! Greetings !!
Here I have added some basic object oriented programs in C++ language. These programs are self explanatory and concepts used are essential to learn object oriented programming.
> Added Object oriented programs in C++

- python codes/removeNthNodeFromEnd.py
Given the `head `of a linked list, remove the `nth `node from the end of the list and return its head.
```
Input: head = [1,2,3,4,5], n = 2
Output: [1,2,3,5]
```
Constraints:
- The number of nodes in the list is `sz`.
- `1 <= sz <= 30`
- `0 <= Node.val <= 100`
- `1 <= n <= sz`
> Add famous question of FAANG companies [removeNthNodeFromEnd.py]

- c codes/india_map.c
> Added India_map.c

- cpp codes/RadixSort.cpp
- cpp codes/dnf-sort.cpp
dnf-sort algo added by GamerNishant
It is important algorithm for sorting 3 numbers input stream in 0(n) time.
> dnf-sort algorithm

- python codes/MinkowskiDistance.md
- python codes/MinkowskiDistance.py
- python codes/gen_table_plus.py
This is an upgrade from the original gen_table.py. Here, TKinter is used to add an additional GUI to the original function of creating the multiplication tables. 
This program calculates the Minkowski Distance given 2 points X and Y using the Minkowski formula. Refer to the MinkowskiDistance.md for more guidelines. 
Please review and provide feedback. Thank you.
> Added GUI for gen_table.py and Added program to calculate Minkowski Distance

- CONTRIBUTING.md
Create CONTRIBUTING.md with detailed steps and instructions for beginners trying to contribute in Hacktoberfest 2020.
Please review and do the needful.
> Create CONTRIBUTING.md with detailed steps

- python codes/rock-paper-scissor.py
rock paper scissor, beat the computer!
> added by dummytarget

- Object Oriented Programming/learn.md
HI.I  added code of  finding simple interest.
> added learn.md

- instagramphotodownloader.py
This application comes handy when you wish to delete an Instagram account but wish to keep your collection of images. As this app uses user credentials to open their account and then look for their friend’s ID and download their photos.
> instagramphotodownloader.py

- README.md
PR for issue #844 . Rectified spelling mistake in README.md. Also added my name in it.
> Rectified spelling mistake in README.md

- README.md
- python codes/Queue.py
- python codes/stack.py
> Python Algorithm
